package:
  format-version: "1.0.0"
  name: "wireless_apps_winc3400"
  type: "application"
  status: "production"
  required: false
  version: "v3.7.1"

  dependencies:
    - name: "bsp"
      type: "package"
      version: "v3.20.1"
    - name: "core"
      type: "package"
      version: "v3.13.5"
    - name: "crypto"
      type: "package"
      version: "v3.8.2"
    - name: "cryptoauthlib"
      type: "package"
      version: "v3.7.5"
    - name: "csp"
      type: "package"
      version: "v3.19.5"
    - name: "dev_packs"
      type: "package"
      version: "v3.18.1"
    - name: "net"
      type: "package"
      version: "v3.12.2"
    - name: "wireless_wifi"
      type: "package"
      version: "v3.11.1"
    - name: "wolfssl"
      type: "package"
      version: "v5.4.0"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "v11.0.1"
      
      
