package:
  format-version: "1.0.0"
  name: "wireless_apps_winc1500"
  type: "application"
  status: "production"
  required: true
  version: "v3.7.0"

  dependencies:
    - name: "bsp"
      type: "package"
      version: "v3.16.1"
    - name: "core"
      type: "package"
      version: "v3.13.1"
    - name: "crypto"
      type: "package"
      version: "v3.8.0"
    - name: "cryptoauthlib"
      type: "package"
      version: "v3.3.3"
    - name: "csp"
      type: "package"
      version: "v3.17.0"
    - name: "dev_packs"
      type: "package"
      version: "v3.17.0"
    - name: "net"
      type: "package"
      version: "v3.10.0"
    - name: "wireless_wifi"
      type: "package"
      version: "v3.9.1"
    - name: "wolfssl"
      type: "package"
      version: "v5.4.0"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "v10.4.6"
      
      
