format_version: v1.0
configName: sam_a5d27_som1_winc3400
folderName: sam_a5d27_som1_winc3400
frameworkPath: D:\H3_SAMD27_WINC1500_Release
processor: ATSAMA5D27CD1G
projectName: sam_a5d27_som1_winc3400
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAMA5D2_DFP\1.7.91\atdf\ATSAMA5D27CD1G.atdf
