configName: sam_e54_xpro_winc3400_freertos
folderName: sam_e54_xpro_winc3400_freertos
format_version: v1.0
frameworkPath: ../../..
processor: ATSAME54P20A
projectName: sam_e54_xpro_winc3400_freertos
settings:
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  DFPPath: .\dev_packs\Microchip\SAME54_DFP\3.6.95\atdf\ATSAME54P20A.atdf
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  MERGE_STRATEGY: USER_ALL
  PackageFilter: bsp;core;crypto;cryptoauthlib;csp;dev_packs;net;quick_docs;usb;wireless_apps_winc3400;wireless_wifi
  TRUSTZONE: 'false'
