format_version: v1.0
type: UniqueComponent
attributes: {id: appWincExampleConf}
children:
- type: Symbols
  children:
  - type: Menu
    attributes: {id: APP_WIFI_AUTH_MENU}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Combo
    attributes: {id: APP_WIFI_AUTH_METHOD_STA}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: WPA}
  - type: String
    attributes: {id: APP_WIFI_WPA_PSK}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
- type: ElementPosition
  attributes: {x: '537', y: '189', id: appWincExampleConf}
