configName: sam_d21_xpro_winc3400
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: ATSAMD21J18A
projectName: ''
settings:
  PackageFilter: bsp;core;crypto;csp;dev_packs;net;quick_docs;usb;wireless_apps_winc3400;wireless_wifi
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMD21_DFP\3.4.116\samd21a\atdf\ATSAMD21J18A.atdf
