format_version: v1.0
type: UniqueComponent
attributes: {id: appWincExampleConf}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: APP_WIFI_WPS_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Combo
    attributes: {id: APP_WIFI_WPS_MODE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: appWincExampleConf, value: PBC}
- type: ElementPosition
  attributes: {x: '650', y: '293', id: appWincExampleConf}
