format_version: v1.0
type: UniqueComponent
attributes: {id: appWincExampleConf}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: APP_WIFI_AP_DHCP_SRV_ADDR}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 192.168.1.1}
  - type: Boolean
    attributes: {id: APP_WIFI_AP_DHCP_SRV_ENABLE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: String
    attributes: {id: APP_WIFI_AP_DHCP_SRV_NETMASK}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Menu
    attributes: {id: APP_WIFI_AUTH_MENU}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Combo
    attributes: {id: APP_WIFI_AUTH_METHOD_AP}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: appWincExampleConf, value: WEP}
      - type: User
        attributes: {value: WEP}
  - type: Combo
    attributes: {id: APP_WIFI_AUTH_METHOD_STA}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: APP_WIFI_CHANNEL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Combo
    attributes: {id: APP_WIFI_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: AP}
  - type: Integer
    attributes: {id: APP_WIFI_TCP_SOCK_BUF_SIZE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: APP_WIFI_TCP_SOCK_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: APP_WIFI_TCP_SOCK_PORT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: String
    attributes: {id: APP_WIFI_WEP_KEY}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Combo
    attributes: {id: APP_WIFI_WEP_KEY_IDX}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
- type: ElementPosition
  attributes: {x: '647', y: '293', id: appWincExampleConf}
